### ISSUE TITLE
Playbook Lookups for better or for worse

### ISSUE THREAD

**Issue by keithresar** [keithresar/ansible-minneapolis-meetup-topics#12]
http://docs.ansible.com/ansible/playbooks_lookups.html

**Comment by wyattwalter** [comment]
Hey @keithresar, I'd be happy to do a generic talk about `lookup` and dive into Credstash as an example. I can't make the January meeting date, though.

**Comment by keithresar** [comment]
Are you available March 15th @wyattwalter?

**Comment by wyattwalter** [comment]
Yep, that would work!

**Comment by keithresar** [comment]
Awesome!
Can you send me an email direct to finalize logistics?

**Comment by wyattwalter** [comment]
Sure, where can I lookup your address?
