### ISSUE TITLE
Automated Testing for Ansible Roles Using Molecule

### ISSUE THREAD

**Issue by keithresar** [keithresar/ansible-minneapolis-meetup-topics#19]
Molecule is designed to aid in the development and testing of Ansible roles including support for multiple instances, operating system distributions, virtualization providers and test frameworks.

It leverages Vagrant, Docker, and OpenStack to manage virtual machines/containers, with support for multiple Vagrant providers (currently VirtualBox, Parallels, VMware Fusion, and Libvirt). Molecule supports Serverspec, Testinfra, or Goss (beta) to run tests. Molecule uses an Ansible playbook (playbook.yml), to execute the role and its tests.

https://github.com/metacloud/molecule

**Comment by keithresar** [comment]
https://zapier.com/engineering/ansible-molecule/

**Comment by JRemitz** [comment]
@keithresar I'd like to present on molecule. I have a strong interest in test driven development with ansible and it's something that we're working through at CWT. It would be great if I can get something together for the August session if it works out.  I can confirm for sure in the next two weeks. Please let me know.
