### ISSUE TITLE
Ansible Tower Demo and Discussion

### ISSUE THREAD

**Issue by keithresar** [keithresar/ansible-minneapolis-meetup-topics#8]
https://www.ansible.com/tower

Extend the power of Ansible to your entire team - scale IT automation, manage complex deployments and speed productivity. Centralize and control your IT infrastructure with a visual dashboard, role-based access control, job scheduling and graphical inventory management.

**Comment by fantashley** [comment]
I'd be happy to speak about Ansible Tower since I set it up at General Mills.
